### PR TITLE
DOC: stats: minor correction

### PR DESCRIPTION
**Pull request by mdhaber**
@steppi

### CODE REVIEW

**Comment by steppi** [comment]
Good catch. I missed that one. I guess I should look over everything again too.

**Review by steppi — APPROVED** [review]
Good catch.

**Comment by mdhaber** [comment]
Oops I didn't mean to just point this out; I meant to open this against the main repo : P I should do that before we branch 1.11 unless you wanted to take a look for other things.

**Comment by steppi** [comment]
> Oops I didn't mean to just point this out; I meant to open this against the main repo : P I should do that before we branch 1.11 unless you wanted to take a look for other things.

I probably won't have time to look for other things. You can go ahead.

**Pull request closed without merging**
